### ISSUE TITLE
missing AUTHORS.md

### ISSUE THREAD

**Issue by arthurlutz** [Pawamoy/cookiecutter-awesome#3]

**Comment by pawamoy** [comment]
I personally don't find an AUTHORS file to be useful so I'm not planning to add one, but if you can share good reasons to have one I can reconsider :relaxed:

**Comment by arthurlutz** [comment]
There's a link in the credits section https://github.com/pawamoy/cookiecutter-awesome/blame/master/%7B%7Bcookiecutter.repository_slug%7D%7D/README.md#L34 ?

I'm fine with removing it ;-)

**Comment by pawamoy** [comment]
Ha, nice catch! Then we'll remove the credits section! Thanks!
